# Gunakan image dasar PHP
FROM php:8.1-cli

# Atur working directory
WORKDIR /app

# Salin composer files dan instal dependensi
COPY composer.json composer.lock /app/
RUN php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');" \
    && php composer-setup.php --install-dir=/usr/local/bin --filename=composer \
    && rm composer-setup.php \
    && composer install --no-interaction --prefer-dist --optimize-autoloader

# Salin seluruh kode aplikasi ke image
COPY . /app

# Ekspose port untuk aplikasi
EXPOSE 8080

# Jalankan aplikasi menggunakan php spark serve
CMD ["php", "spark", "serve", "--host", "0.0.0.0", "--port", "8080"]
